VOICEWEAVER_KEYSTORE=voiceweaver-release.keystore
VOICEWEAVER_KEY_ALIAS=voiceweaver
VOICEWEAVER_STORE_PASSWORD=NMhB4o1dbv3MtoHuei5XPy7puECslEJ6t4HaQNsdTcM=
VOICEWEAVER_KEY_PASSWORD=NMhB4o1dbv3MtoHuei5XPy7puECslEJ6t4HaQNsdTcM=
